version: "3"
name: "gw_test"
services:

  helloService:
    container_name: hello-service
    image: "wiremock/wiremock:latest"
    volumes:
      - ./mocks/helloService:/home/wiremock
    depends_on:
      - keycloak
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 8081:8080

  byeService:
    container_name: bye-service
    image: "wiremock/wiremock:latest"
    volumes:
      - ./mocks/byeService:/home/wiremock
    depends_on:
      - keycloak
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 8082:8080

  secureService:
    container_name: secure-service
    image: "wiremock/wiremock:latest"
    volumes:
      - ./mocks/secureService:/home/wiremock
    depends_on:
      - keycloak
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 8083:8080


  keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:latest"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=insecure
    ports:
     - 8090:8080
     - 8443:8443
  