version: "3"
name: "gw_test"
services:

  helloService:
    extends:
      file: docker-compose.yaml
      service: helloService
    ports:
      - 8081:8080
    environment:
      - CONSUL_SERVICE_PORT=8081
      - SERVICE_ADDRES=host.docker.internal

  byeService:
    extends:
      file: docker-compose.yaml
      service: byeService
    ports:
      - 8082:8080
    environment:
      - CONSUL_SERVICE_PORT=8082
      - SERVICE_ADDRES=host.docker.internal

  secureService:
    extends:
      file: docker-compose.yaml
      service: secureService
    ports:
      - 8083:8080
    environment:
      - CONSUL_SERVICE_PORT=8083
      - SERVICE_ADDRES=host.docker.internal

  discoverableService:
    extends:
      file: docker-compose.yaml
      service: discoverableService
    environment:
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOST=host.docker.internal
    ports:
      - 8084:8080

  keycloak:
    extends:
      file: docker-compose.yaml
      service: keycloak

  consul:
    extends:
      file: docker-compose.yaml
      service: consul
  